-- Portable identity column: GENERATED BY DEFAULT AS IDENTITY is SQL-standard and works on
-- both H2 (test) and Postgres (the integration-test tier / prod), unlike the H2/MySQL-only
-- AUTO_INCREMENT this used to use, which fails on Postgres.
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    body TEXT,
    created_at TIMESTAMP
);
