package com.larvalabs.brace;

import com.larvalabs.brace.testmodels.Post;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Exercises the framework's own {@link DatabaseFactory} — Flyway migrations + Hibernate
 * {@code StatelessSession} — against real Postgres, the path the H2-only suite could never
 * cover. Unlike {@link PostgresSkipLockedClaimIT} (which runs framework migrations directly via
 * Flyway), this goes through {@code DatabaseFactory}, so it also runs the <em>app</em> migration
 * {@code db/migration/V1__create_posts.sql}. That fixture used to use H2/MySQL-only
 * {@code AUTO_INCREMENT} and broke on Postgres; this IT is what now guards the portable
 * {@code GENERATED BY DEFAULT AS IDENTITY} form.
 *
 * <p>It proves end-to-end that (1) framework + app migrations apply on Postgres and (2) an
 * IDENTITY-generated id round-trips through Hibernate. It's also the template for Phase 2 — the
 * existing {@code DatabaseFactory}-based tests ({@code DurableJobTest},
 * {@code MultiInstanceSchedulerTest}, {@code ErrorStoreTest}, …) port onto this same base.
 */
class DatabaseFactoryPostgresIT extends PostgresTestBase {

    static DatabaseFactory factory;

    @BeforeAll
    static void buildFactory() {
        // Base @BeforeAll has started the shared container (and skipped the class if Docker is
        // absent). DatabaseFactory's constructor runs framework + app migrations on it.
        factory = new DatabaseFactory(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword(),
                List.of(Post.class));
    }

    @AfterAll
    static void closeFactory() {
        if (factory != null) {
            factory.close();
        }
    }

    @BeforeEach
    void clean() throws Exception {
        truncate("posts");
    }

    @Test
    void insertsAndReadsThroughHibernateOnPostgres() {
        var db = new Database(factory.openSession());
        try {
            db.beginTransaction();
            var p = new Post();
            p.title = "hello";
            p.body = "from postgres";
            p.createdAt = Instant.now();
            db.insert(p);
            db.commitTransaction();
        } finally {
            db.close();
        }

        var db2 = new Database(factory.openSession());
        try {
            db2.beginTransaction();
            var all = db2.findAll(Post.class);
            db2.commitTransaction();

            assertEquals(1, all.size(), "the inserted row should be readable back on Postgres");
            var found = all.get(0);
            assertNotNull(found.id, "Postgres GENERATED ... AS IDENTITY should populate the id");
            assertEquals("hello", found.title);
            assertEquals("from postgres", found.body);
        } finally {
            db2.close();
        }
    }

    @Test
    void paginateDerivesCountFromAnOrderedQueryOnPostgres() {
        // Postgres rejects an ORDER BY on a non-grouped column next to count(*), so this guards
        // that Hibernate's getResultCount() really drops the ORDER BY from the where-fragment.
        var db = new Database(factory.openSession());
        try {
            db.beginTransaction();
            for (int i = 0; i < 5; i++) {
                var p = new Post();
                p.title = "page_" + i;
                p.body = "b";
                p.createdAt = Instant.now().plusSeconds(i);
                db.insert(p);
            }
            db.commitTransaction();

            db.beginTransaction();
            var page = db.paginate(Post.class, "title LIKE ? ORDER BY createdAt DESC", 2, 2, "page_%");
            db.commitTransaction();

            assertEquals(5, page.totalCount());
            assertEquals(3, page.totalPages());
            assertEquals(List.of("page_2", "page_1"), page.items().stream().map(p -> p.title).toList());

            // An ORDER BY-only fragment lists every row (no "WHERE ORDER BY"), and its count
            // drops the ORDER BY, which Postgres would reject next to count(*).
            db.beginTransaction();
            var all = db.paginate(Post.class, "ORDER BY createdAt DESC", 1, 2);
            long counted = db.count(Post.class, "ORDER BY createdAt");
            db.commitTransaction();
            assertEquals(5, all.totalCount());
            assertEquals(5, counted);
            assertEquals(List.of("page_4", "page_3"), all.items().stream().map(p -> p.title).toList());
        } finally {
            db.close();
        }
    }
}
